version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app:z"
      - "/etc/localtime:/etc/localtime:ro"
    command: gunicorn app.wsgi:application --bind 0.0.0.0:5000
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:example@db/flask'

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:5000