"""empty message

Revision ID: 54c42a7c991c
Revises: 6666a753c860
Create Date: 2023-10-02 10:42:48.860606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c42a7c991c'
down_revision = '6666a753c860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ID')

    # ### end Alembic commands ###
