"""empty message

Revision ID: 81ad23a23a0d
Revises: e3e78ca3c3e6
Create Date: 2023-10-24 09:04:26.854099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ad23a23a0d'
down_revision = 'e3e78ca3c3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sklad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kusy', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sklad', schema=None) as batch_op:
        batch_op.drop_column('kusy')

    # ### end Alembic commands ###
