"""empty message

Revision ID: b08b04387ee1
Revises: 61e9325d77b6
Create Date: 2023-10-02 10:48:32.706386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08b04387ee1'
down_revision = '61e9325d77b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifikator', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['identifikator'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('identifikator')

    # ### end Alembic commands ###
