"""empty message

Revision ID: e3e78ca3c3e6
Revises: a0cf2e919c70
Create Date: 2023-10-24 09:00:56.319108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e78ca3c3e6'
down_revision = 'a0cf2e919c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sklad', schema=None) as batch_op:
        batch_op.drop_column('pocet_kusu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sklad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pocet_kusu', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
