"""empty message

Revision ID: fc247e501ee7
Revises: b08b04387ee1
Create Date: 2023-10-02 10:53:50.803703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc247e501ee7'
down_revision = 'b08b04387ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.alter_column('vyrobce_vozidla',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vyrobce', schema=None) as batch_op:
        batch_op.alter_column('vyrobce_vozidla',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
