"""empty message

Revision ID: fcc39c31adce
Revises: 281ad437e446
Create Date: 2023-10-09 10:08:56.255009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc39c31adce'
down_revision = '281ad437e446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rodic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=50), nullable=True),
    sa.Column('prijmeni', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=50), nullable=True),
    sa.Column('prijmeni', sa.String(length=50), nullable=True),
    sa.Column('rodic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rodic_id'], ['rodic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dite')
    op.drop_table('rodic')
    # ### end Alembic commands ###
